version: '3.8'

services:
  onec:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ONEC_VERSION: ${ONEC_VERSION}
        INSTALLER_PATH: ${INSTALLER_PATH}
        YANDEX_LOGIN: ${YANDEX_LOGIN}
        YANDEX_PASSWORD: ${YANDEX_PASSWORD}
        MAILRU_LOGIN: ${MAILRU_LOGIN}
        MAILRU_PASSWORD: ${MAILRU_PASSWORD}
    image: onec-installer
    ports:
      - "5343:80"        # Для Apache
      - "5901:5901"      # Для VNC
      - "3389:3389"      # Для RDP
    volumes:
      - ./installer:/1c-dist-installer
      - /mnt/yandexDisk:/mnt/yandexDisk
      - /mnt/mailRuDisk:/mnt/mailRuDisk
    privileged: true
    tty: true
    environment:
      YANDEX_LOGIN: ${YANDEX_LOGIN}
      YANDEX_PASSWORD: ${YANDEX_PASSWORD}
      MAILRU_LOGIN: ${MAILRU_LOGIN}
      MAILRU_PASSWORD: ${MAILRU_PASSWORD}
      PAS_SETUP_VNS: ${PAS_SETUP_VNS}  # Передача пароля для VNC
